model:
  base_learning_rate: 2.0e-06
  target: models.mapping_wrapper.MappingWrapper
  params:
    mapping_config:
      target: training.networks.MappingNetwork
      params:
        z_dim: 512                  # Input latent (Z) dimensionality, 0 = no latent.
        c_dim: 1024                      # Conditioning label (C) dimensionality, 0 = no label.
        w_dim: 512               # Intermediate latent (W) dimensionality.
        num_ws: 1                     # Number of intermediate latents to output, None = do not broadcast.
    cond_stage_config:
      target: ldm.modules.encoders.modules.OpenCLIPEncoder
      params:
        scale_factor: 1.0
        type: cls
    style_gan_config:
      target: models.style_gan_wrapper.StyleGANWrapper
      params:
        generator_pth: weights/photomat/G_512.pkl
        decoder_pth: weights/photomat/MatUnet_512.pt
        num_ws: 16
        use_fp16: false

dataloader:
  # RandomNoiseDataLoader
  params:
    seed: 12345
    count: 1000000
    dim: 512
